### ISSUE TITLE
<head>部分を固定したい

### ISSUE THREAD

**Issue by quojama** [zztkm/vss#9]
現状はvss.exeを走らすたびに<head>が上書きされる？と思うのですがcssの読み込みやweb fontの読み込みなど、<head>内はそのままとして、vss.exeを走らせたら.mdを<body>内のみに反映させるようにする？

みたいなのがあれば嬉しいと思いました！

**Comment by zztkm** [comment]
@quojama _index.html に <head> を書いておくで対応できませんか？

**Comment by quojama** [comment]
忘れていました。完璧OKです。もうもはやこれがあれば怖いものなし。これでいわゆるheaderとfooterも作れるな
